# Permalinks
permalink:           pretty

# Setup
title:               Sam Mize
tagline:             Blog
url:                 http://mize1985.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Sam Mize
  email:             samwmize@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/mize1985

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
